### ISSUE TITLE
Short array syntax used, incompatible with PHP 5.3

### ISSUE THREAD

**Issue by jkoudys** [gcds/epwt-cache#1]
On the readme, you say that PHP >= 5.3 is required, however here:
https://github.com/gcds/epwt-cache/blob/master/Core/CacheItem.php#L178

you're using short-array syntax, which wasn't added until 5.4: http://php.net/manual/en/language.types.array.php#language.types.array.syntax.array-func

Please either update the README.md  to only include >= 5.4, or change your short arrays to `array()` syntax. Personally I vote for dropping 5.3 support, since it's now at n-3 versions behind, and anyone savvy enough to  know what Redis or PSR-6 are, are very unlikely to want to use it on a PHP5.3 install.

**Comment by djmattyg007** [comment]
PHP 5.3 is end of life. Support for it should be actively dropped.

**Comment by shadowhand** [comment]
More importantly, the [composer.json lists 5.3](https://github.com/gcds/epwt-cache/blob/3eccd9fdaf3ec7d4df52b2dc5b170158443ad174/composer.json#L15).

**Comment by aurimasniekis** [comment]
I think just will drop support for 5.3 because nobody just uses it as @jkoudys said..
